### ISSUE TITLE
Feature Request: autocomplete with h1 title

### ISSUE THREAD

**Issue by carvinlo** [svsool/memo#117] opened 2020-09-17 07:45 UTC
When linking `02-started.md` document in `01-intro.md` document, it would be greate to be able to bring the h1 title of document `02-started.md`.

e.g. 
`01-intro.md`
```markdown
# Intro
This is some text, link [[02-started|Let's started]]
```
`02-started.md`
```markdown
# Let's started
Do something.
```

**Comment by svsool** [comment] 2020-09-20 14:39
Hi, thanks for the idea.

This can be considered if/when Memo gets content-based indexing. I expect it to be not a small task. Currently, Memo has only a lightweight cache based on workspace filenames. Let's see if I can contribute or more contributors will emerge around Memo.

**Comment by srid** [comment] 2020-09-20 15:22
Once neuron gets static binaries, this is something that can be delegated via https://github.com/srid/neuron/issues/213 (if not LSP, one can use `neuron query ...` to get graph data).

**Comment by carvinlo** [comment] 2020-09-21 13:38
I found that [markdown-notes](https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes) has a similar feature, but it can only be previewed:
![image](https://user-images.githubusercontent.com/5674761/93773121-472ef900-fc52-11ea-88ab-af5315fb30d3.png)

Required configuration:
`.vscode/settings.json`
```json
{
  "[markdown]": {
    "editor.quickSuggestions": true
  }
}

```

**Comment by svsool** [comment] 2022-07-30 08:20
Closing it as duplicate of https://github.com/svsool/memo/issues/19 where it was decided to not implement this feature for now.

Autocomplete preview of the files should be available though.

**Closed by svsool** 2022-07-30 08:20 UTC
