### ISSUE TITLE
Reference header name with code

### ISSUE THREAD

**Issue by sleepymalc** [svsool/memo#584] opened 2022-07-28 20:07 UTC
I ran into a small issue: I want to reference a specific section in other files with a name simply like `code` (plain text like \'code\'). In the same file, I can reference this section by `#code`, but in another file, I can't reference this section as other sections with regular names. For example, `[[file#code]]` won't work. Is there any hope to make this work?

Another problem with wikilink is that the character `[` and `]` is parsed in the wrong way inside of `[[wikilink]]`. For example, `[[this is a paper[by this author]]]` won't work.

**Comment by svsool** [comment] 2022-07-30 07:44
Hi, this feature looks like a duplicate of [this one](https://github.com/svsool/memo/issues/19), previously I decided to not implement it because of possible inconsistencies related to link synchronization if header is edited.

`[`, `]` characters are not allowed.

Thank you!

**Closed by svsool** 2022-07-30 07:44 UTC
